package com.ot.Herbal360.dto;

import java.time.LocalDate;
import java.time.LocalDateTime;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;

import org.hibernate.annotations.UpdateTimestamp;

import com.fasterxml.jackson.annotation.JsonManagedReference;

import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

@Entity
@Data
public class Customer {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@ApiModelProperty(value = "AutoGenerated")
	private long id;

	@NotBlank(message = "Please Enter The Customer-Name")
	@ApiModelProperty(required = true)
	private String name;

	@NotNull(message = "Please Enter The Customer-Age")
	@ApiModelProperty(required = true)
	private int age;

	@NotBlank(message = "Please Enter The Customer-Gender")
	@ApiModelProperty(required = true)
	private String gender;

	@Column(unique = true)
	@NotBlank(message = "Please Enter The Customer-PhoneNumber")
	@ApiModelProperty(required = true)
	@Pattern(regexp = "^[6-9]{1}[0-9]{9}+$", message = "Enter Proper Customer-PhoneNumber")
	private String phone;

	@Column(unique = true)
	@NotBlank(message = "Please Enter The Customer-Email")
	@Pattern(regexp = "^[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+$", message = "Enter a Valid Customer-Email")
	@ApiModelProperty(required = true)
	private String email;

	@NotBlank(message = "Please Enter The Customer-Address")
	@ApiModelProperty(required = true)
	private String address;

	@ApiModelProperty(required = true)
	private LocalDate joiningTime;

	@UpdateTimestamp
	private LocalDateTime updatedTime;

	@ApiModelProperty(required = true)
	private LocalDate endingTime;

	@ApiModelProperty(required = true)
	private String uuid;

	@OneToOne
	@JoinColumn
	@JsonManagedReference("plan")
	private Plan plan;

	public Customer(long id, @NotBlank(message = "Please Enter The Customer-Name") String name,
			@NotNull(message = "Please Enter The Customer-Age") int age,
			@NotBlank(message = "Please Enter The Customer-Gender") String gender,
			@NotBlank(message = "Please Enter The Customer-PhoneNumber") @Pattern(regexp = "^[6-9]{1}[0-9]{9}+$", message = "Enter Proper Customer-PhoneNumber") String phone,
			@NotBlank(message = "Please Enter The Customer-Email") @Pattern(regexp = "^[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+$", message = "Enter a Valid Customer-Email") String email,
			@NotBlank(message = "Please Enter The Customer-Address") String address, LocalDate joiningTime, Plan plan) {
		super();
		this.id = id;
		this.name = name;
		this.age = age;
		this.gender = gender;
		this.phone = phone;
		this.email = email;
		this.address = address;
		this.joiningTime = joiningTime;
		this.plan = plan;
	}

	public Customer() {
		super();
	}

}