package com.ot.Herbal360.dto;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonBackReference;

import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

@Data
@Entity
public class Plan {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@ApiModelProperty(value = "AutoGenerated")
	private long id;
	
	@NotBlank(message = "Please Enter The Plan-Name")
	@ApiModelProperty(required = true)
	private String name;
	
	@NotBlank(message = "Please Enter The Plan-Description")
	@ApiModelProperty(required = true)
	private String description;
	
	@NotBlank(message = "Please Enter The Plan-Image")
	@ApiModelProperty(required = true)
	private String image;
	
	@NotNull(message = "Please Enter The Plan-Duration")
	@ApiModelProperty(required = true)
	private int duration;
	
	@OneToOne(mappedBy = "plan")
	@JsonBackReference("plan")
	private Customer customer;

	public Plan(long id, @NotBlank(message = "Please Enter The Plan-Name") String name,
			@NotBlank(message = "Please Enter The Plan-Description") String description,
			@NotBlank(message = "Please Enter The Plan-Image") String image,
			@NotNull(message = "Please Enter The Plan-Duration") int duration, Customer customer) {
		super();
		this.id = id;
		this.name = name;
		this.description = description;
		this.image = image;
		this.duration = duration;
		this.customer = customer;
	}

	public Plan() {
		super();
		// TODO Auto-generated constructor stub
	}
	
	
}
