package com.ot.Herbal360.dto;

import java.time.LocalDate;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.validation.constraints.NotNull;

import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
public class PlanProduct {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@ApiModelProperty(value = "AutoGenerated")
	private long id;
	
	@NotNull(message = "Please Enter The Plan-Id")
	@ApiModelProperty(required = true)
	private long planId;
	
	@NotNull(message = "Please Enter The Product-Id")
	@ApiModelProperty(required = true)
	private long productId;
	
	@NotNull(message = "Please Enter Days")
	@ApiModelProperty(required = true)
	private int days;
	
	@ApiModelProperty(required = true)
	private LocalDate sheduledTime;

}
