package com.ot.Herbal360.dto;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.validation.constraints.NotBlank;

import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

@Data
@Entity
public class Product {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@ApiModelProperty(value = "AutoGenerated")
	private long id;
	
	@NotBlank(message = "Please Enter The Plan-Name")
	@ApiModelProperty(required = true)
	private String name;
	
	@NotBlank(message = "Please Enter The Plan-Description")
	@ApiModelProperty(required = true)
	private String description;
	
	@NotBlank(message = "Please Enter The Plan-Image")
	@ApiModelProperty(required = true)
	private String image;

	public Product(long id, @NotBlank(message = "Please Enter The Plan-Name") String name,
			@NotBlank(message = "Please Enter The Plan-Description") String description,
			@NotBlank(message = "Please Enter The Plan-Image") String image) {
		super();
		this.id = id;
		this.name = name;
		this.description = description;
		this.image = image;
	}

	public Product() {
		super();
		// TODO Auto-generated constructor stub
	}
	
	
}
